"""Pre-render project cards, detail pages, research and assistant data. No dependencies."""
from pathlib import Path
from html import escape as e
import json
import re

ROOT = Path(__file__).resolve().parents[1]
projects = json.loads((ROOT / 'data/projects.json').read_text(encoding='utf-8'))['projects']
papers = [p for p in projects if p.get('paper')]

def paper_link(p):
    return 'https://doi.org/' + p['paper']['doi']

def figure(src, alt, caption, width=800, height=620, css='case-cover'):
    return f'<figure class="{css}"><img src="../{e(src)}" alt="{e(alt)}" width="{width}" height="{height}" loading="lazy" decoding="async"><figcaption class="mono">{e(caption)}</figcaption></figure>'

cards = []
for p in projects:
    cards.append(f'''<article class="project-card" id="panel-{p['id']}"><a class="project-card-link" href="projects/{p['slug']}.html" aria-labelledby="project-{p['id']}" aria-describedby="summary-{p['id']}"><div class="project-card-image"><img src="{p['image']}" alt="{e(p['alt'])}" width="800" height="620" loading="lazy" decoding="async"><span class="project-card-arrow" aria-hidden="true">↗</span></div><div class="project-card-copy"><h3 id="project-{p['id']}">{e(p['name'])}</h3><p id="summary-{p['id']}">{e(p['teaser'])}</p></div></a></article>''')

research = []
for number, p in enumerate(sorted(papers, key=lambda p: p['paper']['year'], reverse=True), 1):
    paper = p['paper']
    research.append(f'''<article class="research-entry" id="paper-{p['id']}" aria-labelledby="paper-title-{p['id']}"><div class="research-meta mono"><span>{number:02} / {paper['year']}</span><span>{e(paper['venue'])}</span></div><div><h3 id="paper-title-{p['id']}">{e(paper['title'])}</h3><p class="research-description">{e(paper['description'])}</p><p class="research-role mono">{e(paper['role'])}</p></div><div class="research-links"><a class="text-link publication-card" href="{paper_link(p)}" target="_blank" rel="noopener noreferrer">Read paper <span aria-hidden="true">↗</span></a><a class="text-link" href="projects/{p['slug']}.html">Related project <span aria-hidden="true">↗</span></a><small class="mono">DOI / {paper['doi']}</small></div></article>''')

index = ROOT / 'index.html'
content = index.read_text(encoding='utf-8')
for name, markup in [('featured', '<div class="project-grid">'+'\n'.join(cards)+'</div>'), ('research', '\n'.join(research))]:
    pattern = rf'(<!-- generated:{name}:start -->).*?(<!-- generated:{name}:end -->)'
    content, count = re.subn(pattern, lambda m: m[1]+'\n'+markup+'\n'+m[2], content, flags=re.S)
    if count != 1: raise ValueError(f'Expected one {name} content region')
index.write_text(content, encoding='utf-8')
# Local-file friendly: no fetch is needed to keep the assistant's detailed answers.
(ROOT/'data/project-content.js').write_text('// Generated by scripts/build-content.py; edit data/projects.json.\nwindow.PortfolioProjects = '+json.dumps(projects, ensure_ascii=False).replace('<', '\\u003c')+';\n', encoding='utf-8')

out = ROOT / 'projects'
out.mkdir(exist_ok=True)
for i, p in enumerate(projects):
    other = projects[(i+1) % len(projects)]
    paper = p.get('paper')
    links = f'<a class="case-link" href="{p["repository"]}" target="_blank" rel="noopener noreferrer">View GitHub ↗</a>'
    if paper: links += f'<a class="text-link" href="{paper_link(p)}" target="_blank" rel="noopener noreferrer">Read publication ↗</a>'
    sections = [f'<section class="case-section" id="overview"><p class="mono">01 / Overview</p><div><h2>About the project.</h2><p>{e(p["summary"])}</p></div></section>']
    if p.get('problem'):
        sections.append(f'<section class="case-section" id="problem"><p class="mono">Context</p><div><h2>The problem.</h2><p>{e(p["problem"])}</p></div></section>')
    sections.append(f'<section class="case-section" id="features"><p class="mono">02 / Features</p><div><h2>What it does.</h2><ul>{"".join("<li>"+e(x)+"</li>" for x in p["features"])}</ul></div></section>')
    if p.get('contributions'):
        sections.append(f'<section class="case-section" id="contribution"><p class="mono">My contribution</p><div><h2>What I worked on.</h2><ul>{"".join("<li>"+e(x)+"</li>" for x in p["contributions"])}</ul><p class="case-credit">Team: Anjana B, {e(", ".join(p["team"]))}.<br>Guide: {e(p["guide"])}.</p></div></section>')
    engineering = ''.join(f'<p>{e(p[key])}</p>' for key in ['approach','engineering'] if p.get(key))
    flow = ''.join(f'<li><span class="mono">{n:02}</span><strong>{e(item)}</strong></li>' for n,item in enumerate(p['workflow'],1))
    sections.append(f'<section class="case-section" id="approach"><p class="mono">03 / Technology</p><div><h2>How it comes together.</h2>{engineering}<ol class="architecture-flow" aria-label="Component overview">{flow}</ol><p class="mono">Component overview / project concept</p><dl class="spec-list"><div><dt>Technology</dt><dd>{e(" · ".join(p["stack"]))}</dd></div></dl></div></section>')
    screenshots = p.get('screenshots', [])
    visuals = ''.join(figure(s['src'],s['alt'],s['caption'],s['width'],s['height'],'case-screenshot') for s in screenshots)
    if not visuals: visuals = figure(p['image'],p['alt'],'Concept illustration / not an application screenshot',css='case-screenshot')
    visual_heading = 'Application screenshots.' if screenshots else 'Project visual.'
    sections.append(f'<section class="case-section" id="visuals"><p class="mono">04 / Visuals</p><div><h2>{visual_heading}</h2><div class="case-gallery">{visuals}</div></div></section>')
    if paper:
        photo = figure(p['photo'],p['photoAlt'],p['photoCaption'],p['photoWidth'],p['photoHeight'],'case-photo')
        sections.append(f'<section class="case-section" id="outcome"><p class="mono">Outcome</p><div><h2>From project to publication.</h2><p>{e(p["outcome"])}</p><a class="text-link" href="{paper_link(p)}" target="_blank" rel="noopener noreferrer">{e(paper["venue"])} {paper["year"]} paper ↗</a>{photo}</div></section>')
    sections.append(f'<section class="case-section" id="links"><p class="mono">05 / Explore</p><div><h2>Explore the work.</h2><div class="project-actions">{links}</div></div></section>')
    facts = f'<span class="mono">{e(" · ".join(p["stack"]))}</span>'
    if paper: facts += f'<span class="mono">Team project · {e(paper["role"])} / {e(paper["venue"])}</span>'
    page = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f6f8f8">
<title>{e(p['name'])} — Anjana B / Project</title><meta name="description" content="{e(p['summary'])}">
<link rel="icon" href="../favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="../editorial.css?v=20260922-3"></head>
<body class="case-page"><a class="skip-link" href="#main">Skip to project details</a>
<header class="case-header wrap"><a class="brand" href="../index.html#home">anjana.b</a><nav class="mono" aria-label="Project navigation"><a href="../index.html#work">All projects ↗</a><a href="../index.html#research">Research</a><a href="../index.html#contact">Contact</a></nav></header>
<main id="main" class="wrap"><header class="case-hero"><p class="mono">{e(p['category'])}{' / '+p['year'] if p.get('year') else ''}</p><h1>{e(p['name'])}</h1><p class="case-summary">{e(p['teaser'])}</p><div class="case-facts">{facts}</div><div class="project-actions">{links}</div></header>
<nav class="case-index mono" aria-label="On this page"><a href="#overview">Overview</a><a href="#features">Features</a><a href="#approach">Technology</a><a href="#visuals">Visuals</a><a href="#links">Links</a></nav>
{''.join(sections)}
<footer class="case-next"><span class="mono">Next project</span><a href="{other['slug']}.html">{e(other['name'])} ↗</a><a class="text-link" href="../index.html#work">Back to all projects</a></footer></main>
<footer class="site-footer wrap"><a class="brand" href="../index.html#home">anjana.b</a><a class="mono" href="../index.html#contact">Let's connect ↗</a></footer></body></html>'''
    (out / (p['slug']+'.html')).write_text(page, encoding='utf-8')
print(f'Generated {len(projects)} cards and detail pages, {len(papers)} papers, and shared assistant data.')
